---
title: "Your A4 Report Title (TODO: Revise title)"
author: "Alani Gayles"
date: '2022-11-22'
output: html_document
---

```{r echo=FALSE, eval=TRUE, message=FALSE}
source("../source/a4-helpers.R")
source("../source/analysis.R")
```

## Abstract 
Incarceration in the United States have had a focus in smaller rural communities with number that are larger than that compared to big cities. This causes problems such as higher poverty rates, a thin safety net, and unnecessary taxpayer dollars to locking up vulnerable citizens. 

## Introduction 
  In this assignment, my goal is to expose patterns of inequalities in the American jail system. Throughout the last couple of decades, incarceration numbers have continued to grow at a fast rate, with 90% being male and the other 10% in prisons and jails being women. Criminal activity, prisons, and jails are usually made up with men from similar communities and possibly families leaving women at home alone raising children, and men confronting possibilities of separation from society and their family. 
  With this data, the direct stakeholders are the prison facilities and government who collect the people and data within the prison. The indirect stakeholders are those who are in jail and their families who are waiting for them. There are thousands of people in jail for life because of race, gender, petty crimes that are now legalized, and much more. These people are now just data points being collected. 

## Data Summary 
[TODO]

[TODO ... other sections ... See Canvas for details]

_All the very best with your work!_

